"""Add AQI NEWS Table

Revision ID: 6e2886d8918e
Revises: 8a1ec854dfb6
Create Date: 2025-07-01 14:34:45.417911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e2886d8918e'
down_revision = '8a1ec854dfb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aqi_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aqi_news')
    # ### end Alembic commands ###
