"""Add AQINews table

Revision ID: a285e72a3cd7
Revises: 6e2886d8918e
Create Date: 2025-07-01 16:02:38.657506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a285e72a3cd7'
down_revision = '6e2886d8918e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aqi_news', schema=None) as batch_op:
        batch_op.alter_column('headline',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=300),
               existing_nullable=False)
        batch_op.alter_column('topic',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aqi_news', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('topic',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('headline',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
